urls.py
from django.conf.urls import url
from rest_framework import routers
from .views import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'contents', views.ContentsViewSet)

app_name = 'bonghwa'
urlpatterns = [
    url(r'^$', views.index, name='index'),

    #auth
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^login/$', views.authentication, name='authentication'),
    url(r'^logout/$', views.logout, name='logout'),
    url(r'^passChg/$', views.passChg, name='passChg'),

    #contents
    url(r'^insertContents/$', views.InsertContents.as_view(), name='insertContents'),
    url(r'^api/(?P<api>[a-z]+)/cpage/(?P<cpage>[0-9]+)', views.GetContents.as_view()),
    url(r'^api/deleteConts/(?P<id>[0-9]+)/', views.DeleteContents.as_view()),
    url(r'^api/viewMention/', views.ViewMention.as_view(), name='viewMention'),
    url(r'^new/(?P<created_date>[0-9]+)/', views.Newfirewood.as_view()),

    #webSocket
    url(r'^activeSession/$', views.ActiveSession.as_view(), name='activeSession'),
    url(r'^deactiveSession/$', views.DeActiveSession.as_view(), name='deactiveSession'),
    url(r'^getSession/$', views.GetSession.as_view(), name='getSession'),
]

templates/html/header.html
{% extends 'html/index.html' %}

{% block header %}
<div id="header">
    <div id="left_header">
        <ul>
            <li @click="set_contents('all', '1')">전체</li>
            <li @click="set_contents('to', '1')">보낸멘션</li>
            <li @click="set_contents('from', '1')">받은멘션</li>
        </ul>
    </div>
    <div id="right_header">
        <ul>
            <li onClick="javascript:location.href='/logout'">로그아웃</li>
        </ul>
    </div>
</div>

<script>
    var ticket = false;
    var firewoodGetter = new Vue({
        el: '#header',
        data: {
            api: 'all',
            cpage: '1',
        },
        created (){
            this.get_contents()
        },
        methods: {
            set_contents (api, cpage){
                this.api = api
                this.cpage = cpage
                this.get_contents()
            },
            get_contents (){
                /* using JSONPlaceholder */
                const baseURI = 'http://127.0.0.1:8000';
                axios.get(`${baseURI}/api/${this.api}/cpage/${this.cpage}`)
                .then((result) => {
                    if(result.data.contentList.length === 0){
                        this.cpage -= 1
                        return false
                    }
                    
                    if(this.cpage == 1){
                        firewood.all_contents = []
                    }

                    for(var i in result.data.contentList){
                        firewood.all_contents.push(result.data.contentList[i])
                    }
                    
                    this.$nextTick(function(){
                        if(this.api == 'all' && this.cpage == 1){
                            firewood.last_index = result.data.contentList[0].created_date
                            firewood.get_new_firewood_count()
                        }
                    });
                })
            },
        }
    })

    window.addEventListener('scroll', function(event){
        var s = window.pageYOffset
        var h = window.innerHeight
        var b = document.documentElement.scrollHeight
        
        if(!ticket && Math.floor(s) + h > b - 2){
            ticket = true;
            firewoodGetter.cpage = Number(firewoodGetter.cpage) + 1
            firewoodGetter.get_contents()

            setTimeout(function(){ ticket = false; }, 5000)
        }
    })
</script>
{% endblock %}

templates/html/index.html
<!DOCTYPE html>
{% load staticfiles %}
{% load bootstrap3 %}

<html lang="ko">
<head>
    <meta charset="UTF-8">
    <title>BONGHWA</title>
    <script src="https://unpkg.com/axios/dist/axios.min.js"></script>
    <script src="https://unpkg.com/vue/dist/vue.js"></script>
    <script src="https://unpkg.com/vue-router/dist/vue-router.js"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script type="text/javascript" src="{% static 'js/ws4redis.js' %}"></script>
    <script>Vue.prototype.$http = axios</script>
    <link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}" >
    <link rel="stylesheet" type="text/css" href="{% static 'css/header.css' %}" >
</head>
<body>
    {% block header %}
    {% endblock %}

    {% block main %}
    {% endblock %}

    {% block right %}
    {% endblock %}

    {% block login %}
    {% endblock %}

    {% block passChg %}
    {% endblock %}

    <!-- <div id="app">
        <router-view></router-view>
    </div>
    <script>
        const router = new VueRouter({
            routes: [
                {
                    path: '',
                    component: App
                }
            ]
        })

        const app = new Vue({
            router
        }).$mount('#app')
    </script> -->
</body>
</html>

templates/html/login.html
{% extends 'html/index.html' %}

{% block login %}

<h2>로그인</h2>

<div id="loginCont">
    <form method="post" action="{% url 'bonghwa:authentication' %}">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="로그인" />
    </form>
        <input @click="signup" type="button" value="회원가입" />
        <input @click="pass_change" type="button" value="비밀번호 찾기" />
    <p>{{ error }}</p>
</div>

<script>
    new Vue({
        el: '#loginCont',
        methods: {
            signup: function(){
                location.href="/signup/";
            },
            pass_change: function(){
                location.href="/passChg/"
            },
        }
    })
</script>
{% endblock %}

templates/html/main.html
{% extends 'html/right.html' %}

{% block main %}
    <div id="left">
        <div class="main_text_cont">
            <form id="insert_form" name="insert_form" action="{% url 'bonghwa:insertContents' %}" method="post" enctype="multipart/form-data" novalidate>
                {% csrf_token %}
                {{ form.contents }}
                {{ form.image }}
                {{ form.mention_index }}
                {{ form.mention_order }}
                <div style="position: relative;">
                    <button id="submit_btn" type="submit">등록</button>
                    <span onClick="javascript:document.getElementById('id_image').click()" id="imagebutton">이미지</span>
                    <span id="imagename" name="imagename" v-text="select_img"></span>
                </div>
            </form>
        </div>
        <div v-if="new_firewood_count > 0" @click="get_new_firewood()">
            <p v-text="new_firewood_count_view"></p>
        </div>
        <div class="main_content_cont" v-for="(content, index) in all_contents" :key="content.id">
            <div class="content_id" >
                <span class="content_id_val"
                      @click="send_firewood(content.username, content.id, content.mention_index, content.mention_order)"
                      v-text="content.username">
                </span>
            </div>
            <div class="content_content" id="content">
                 <span @click="open_mention(index)" v-html="set_firewood(content.contents)"></span>
                 <span v-if="content.image != null && content.image != ''" 
                       @click="open_image(content.image, index)"
                       style="color:blue;">[이미지]</span>
            </div>
            <div class="content_reg_date" v-text="set_date(content.created_date)"></div>
            <div class="btn_delete" @click="delete_firewood(content.id)">[x]</div>
            <div class="mention_cont close" @click="open_mention(index)" v-html="content.mention"></div>
            <div class="image_cont close" @click="close_image()"></div>
        </div>
    </div>
    
    <script>
        var firewood = new Vue({
            el: '#left',
            data: {
                firewood_id : '',
                firewooded: '',
                username: '{{ username }}',
                all_contents: [],
                new_contents: [],
                last_index: '',
                new_firewood_count: 0,
                new_firewood_count_view: '',
                select_img: ''
            },
            methods: {
                send_firewood: function(value, id, mention_index, mention_order){
                    this.firewood_id = '@' + value + ' ' + this.firewood_id

                    if(mention_order == 0){
                        document.getElementById('id_mention_index').value = (id)
                    }
                    else {
                        document.getElementById('id_mention_index').value = (mention_index)
                    }

                    document.getElementById('id_mention_order').value = (Number(mention_order) + 1)
                },
                get_new_firewood_count: function(){
                    var index = this.last_index;
                    setTimeout(function(){
                        const baseURI = 'http://127.0.0.1:8000';
                        axios.get(`${baseURI}/new/${index}`)
                        .then((result) => {
                            var data = result.data.contentList;
                            console.log(data)
                            if(data.length > 0){
                                firewood.new_contents = data.concat(firewood.new_contents)
                                firewood.last_index = data[0].created_date;
                                firewood.new_firewood_count += data.length
                                firewood.new_firewood_count_view = '새 멘션이 ' + firewood.new_firewood_count + '개'
                            }
                            firewood.get_new_firewood_count()
                        });
                    }, 10000);
                },
                get_new_firewood: function(){
                    this.new_firewood_count = 0
                    this.all_contents = this.new_contents.concat(this.all_contents)
                    this.new_contents = []
                },
                set_firewood: function(value){
                    var target = '@' + this.username
                    var text = '<span class="targetId">' + target + '</span>'
                    var re = new RegExp(target, 'g');

                    return value.replace(re, text)
                },
                set_date: function(value){
                    var date = value.substr(0, 4) + '-' + value.substr(4, 2) + '-' + value.substr(6, 2) + ' ' + value.substr(8, 2) + ':' + value.substr(10, 2) + ':' + value.substr(12, 2)
                    return date
                },
                delete_firewood: function(id){
                    $.ajaxSetup({
                        beforeSend(xhr, settings) {
                            xhr .setRequestHeader ( "X-CSRFToken" ,  "{{ csrf_token }}" );
                        }
                    });

                    $.ajax({
                      url:'http://127.0.0.1:8000/api/deleteConts/' + id + '/',
                      type:'DELETE',
                      data:{'id': id},
                      success:function(response){
                        firewood.get_contents();
                      },
                      error:function(error){
                        console.log(error);
                      }
                    });
                },
                open_mention: function(index){
                    var target = document.getElementsByClassName('mention_cont')[index]
                    var className = target.className

                    target.className = (className == 'mention_cont close')?'mention_cont open':'mention_cont close'
                },
                onChangeImg: function(e){
                    var files = e.target.files || e.dataTransfer.files;
                    
                    if (!files.length) {
                        return;
                    }
                    
                    this.select_img = files[0].name;
                },
                open_image: function(image, index){
                    var target = document.getElementsByClassName('image_cont')[index]
                    var className = target.className
                    var html = target.innerHTML

                    if(html == null || html == ''){
                        target.innerHTML = '<img src="/media/' + image + '" />'
                    }

                    target.className = (className == 'image_cont close')?'image_cont open':'image_cont close'
                },
            }
        })

        document.addEventListener('keyup', function(e){
            var key = e.which || e.keyCode
            if(key === 13){
                document.insert_form.submit();
            }
        })
    </script>
{% endblock main %}

templates/html/passChg.html
{% extends 'html/index.html' %}

{% block passChg %}

<div id="passChg_cont">
    <h2>비밀번호 변경</h2>
    <form method="post" url="{% url 'bonghwa:passChg' %}">
        {% csrf_token %}
        <p>id: <input type="text" name="username" value="" /></p>
        <p>password: <input type="password" name="password" value="" v-model="password" /></p>
        <p>password confirm: <input type="password" name="pass_confirm" value="" v-model="pass_confirm" /></p>
        <input @click="pass_check" type="submit" value="비밀번호 변경" />
    </form>
</div>

<script>
    new Vue({
        el: '#passChg_cont',
        data: {
            password: '',
            pass_confirm: '',
        },
        methods: {
            pass_check: function(e){
                if(this.password != this.pass_confirm){
                    alert("입력한 비밀번호가 다릅니다.");
                    e.preventDefault();
                    return false;
                }
            },
        }
    })
</script>
{% endblock %}

templates/html/right.html
{% extends 'html/header.html' %}

{% block right %}
<div id="right">
    {% include 'html/right/user.html' %}
</div>
{% endblock %}